### ISSUE TITLE
week 6 exercise 7

### ISSUE THREAD

**Issue by neodyymi** [jttoivon/x#11]
line 27-28 should be:
```
def get_features_and_labels(filename):
    return (np.array([[]]), np.array([]))
```

**Comment by neodyymi** [comment]
Also the instructions say:

>  If you want, you can visualize the clustering using the provided plot function.

But the tests check that it's been used..

**Comment by neodyymi** [comment]
I also seem to be able to use _AgglomerativeClustering_ with `affinity='hamming'` for same results as with _pairwise_distances_

**Comment by jttoivon** [comment]
All fixed.

By the documentation (below) the string 'hamming' should not be possible, but the function
hamming should be possible. But it seems all three ways work. Maybe I will stick with the original one though, since I wanted to plot the heatmap and dendrograms, which needs the distance matrix.


affinity : string or callable, default: “euclidean”

    Metric used to compute the linkage. Can be “euclidean”, “l1”, “l2”, “manhattan”, “cosine”, or ‘precomputed’. If linkage is “ward”, only “euclidean” is accepted.
